export const TYPES = {
    GET_CONFIG: "GET_CONFIG",
    SET_CONFIG: "SET_CONFIG",
    GET_URL: "GET_URL",
    SET_URL: "SET_URL",
    GET_EVENT_MATCH: "GET_EVENT_MATCH",
    SET_EVENT_MATCH: "SET_EVENT_MATCH",
    SET_LEAGUE_TABLE: "SET_LEAGUE_TABLE",
    GET_LEAGUE_TABLE: "GET_LEAGUE_TABLE"
}
